name: Test
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
        
         - name: Setup Python
           uses: actions/setup-python@v1  
           with:
            python-version: 3.7

         - name: Install Python Dependencies With Pip
           run: pip install -r requirements.txt

         - name: Run Unit Tests
           run: pytest
    build_and_deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Build Docker Image
          run: docker image build -t gcr.io/myflaskdemo/demo-app:2.0 .

        - name: Test retrieving the commit hash from Github Actions.
          run: echo $(git rev-parse --short "$GITHUB_SHA")

        - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
            service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            export_default_credentials: true

        - name: Push To Google Cloud Container Registry
          run: gcloud auth configure-docker && docker push gcr.io/myflaskdemo/demo-app:2.0
        
        - name: Configure Kubectl With Cluster Credentials From GKE
          run: gcloud container clusters get-credentials demo-app-cluster --region us-central1 --project myflaskdemo

        - name: Deploy To GKE Cluster
          run: kubectl apply -f deployment.yaml
