name: Test
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
        
         - name: Setup Python
           uses: actions/setup-python@v1  
           with:
            python-version: 3.7

         - name: Install Python Dependencies With Pip
           run: pip install -r requirements.txt

         - name: Run Unit Tests
           run: pytest
    build_and_deploy:
        needs: [test]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Build Docker Image
          run: docker image build -t gcr.io/myflaskdemo/demo-app:1.0 .

        - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
          with:
            service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
            service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
            export_default_credentials: true

        - name: Push To Google Cloud Container Registry
          run: gcloud  auth configure-docker && docker push gcr.io/myflaskdemo/demo-app:1.0

        - name: Deploy To GKE Cluster
          run: kubectl apply -f deployment.yaml
